##################################################
# global configure
##################################################

def Settings(**kwargs):
	return { 
		"flags": [
            "-x", 
            "c++",
            "-std=c++11",
            "-Wall",
            "-Werror",
            "-I.",
            "-I/home/nickwu/QQMail/",
            "-I/home/nickwu/QQMail/build64_debug",
            "-I/home/nickwu/QQMail/build64_release",
            "-I/home/nickwu/QQMail/build64_fastbuild",
            "-I/home/nickwu/QQMail/comm",
            "-I/home/nickwu/QQMail/comm2",
            "-I/home/nickwu/QQMail/comm2/summer",
            "-I/home/nickwu/QQMail/comm2/tlvpickle",
            "-I/home/nickwu/QQMail/comm2/core",
            "-I/home/nickwu/QQMail/comm2/svrkit",
            "-I/home/nickwu/QQMail/mmsearch",
            "-I/home/nickwu/QQMail/mmsearch2",
            "-I/home/nickwu/QQMail/wqueue",
            "-I/home/nickwu/QQMail/platform",
            "-I/home/nickwu/QQMail/mm3rd",
            "-I/home/nickwu/QQMail/mm3rd2",
            "-I/home/nickwu/QQMail/mm3rd/rapidjson/include/",
            "-I/home/nickwu/QQMail/mm3rd/boost/",
            "-I/home/nickwu/QQMail/mm3rd/curl/include/",
            "-I/home/nickwu/QQMail/mm3rd/hadoop/libhdfs/",
            "-I/home/nickwu/QQMail/mm3rd/jsoncpp/include/",
            "-I/home/nickwu/QQMail/mm3rd/jsoncpp/include/json/",
            "-I/home/nickwu/QQMail/mm3rd/l5client/",
            "-I/home/nickwu/QQMail/mm3rd/mysql/",
            "-I/home/nickwu/QQMail/mm3rd/protobuf/include/",
            "-I/home/nickwu/project/",
            "-I~/code/leveldb",
            "-I~/code/leveldb/include",
            "-I~/code/rocksdb",
            "-I~/code/hbase",
            "-I~/code/httpproxy",
            "-I~/code/gowork/",
            "-I~/code/",
            "-I~/bigdata/ClickHouse",
            "-I~/bigdata/ClickHouse/src",
            "-I~/bigdata/terarkdb",
            "-I~/bigdata/influxdb/",
            "-I~/bigdata/",
            "-I/usr/include/",
            "-I/usr/local/include/",
        ],
	}

