#!/bin/sh

function clean()
{
    sudo rm -f ~/.vimrc
    sudo rm -f ~/.viminfo
    sudo rm -rf ~/.vim/plugged
}

function main()
{
    clean

    ln -s ~/.vim/vimrc ~/.vimrc
    vim -c :PlugInstall -c :q -c :q
    python3 ~/.vim/plugged/YouCompleteMe/install.py --all

    echo "!!! vim evn install success !!!"
}

main

