#!/bin/sh

function clean()
{
    sudo rm -f ~/.vimrc
    sudo rm -f ~/.viminfo
    sudo rm -rf ~/.vim/plugged
}

function installvim()
{
    rm -rf ~/.vim/latest
    mkdir ~/.vim/latest
    cd ~/.vim/latest

    wget -O vim_v9.1.0927.tar.gz https://github.com/vim/vim/archive/refs/tags/v9.1.0927.tar.gz
    tar -zxvf vim_v9.1.0927.tar.gz
    cd vim-9.1.0927

    if [ -f "/cbs/gcc-14.2.0/bin/gcc" ]; then
      export CC="/cbs/gcc-14.2.0/bin/gcc"
      export CXX="/cbs/gcc-14.2.0/bin/g++"
      export CFLAGS="-I/data/home/nickwu/.miniconda3/envs/my/include/"
      export CXXFLAGS="-I/data/home/nickwu/.miniconda3/envs/my/include/"
      export LDFLAGS="-L/data/home/nickwu/.miniconda3/envs/my/lib/ -lpython3"
    fi

    ./configure \
        --with-features=huge \
        --enable-multibyte \
        --with-tlib=tinfo \
        --enable-rubyinterp=yes \
        --enable-python3interp=yes \
        --enable-perlinterp=yes \
        --enable-luainterp=yes \
        --enable-gtk3-check \
        --enable-cscope
    make -j 10
    sudo make install

    cd ~
}

function main()
{
    #clean
    installvim

    ln -s ~/.vim/vimrc ~/.vimrc
    vim -c :PlugInstall -c :q -c :q
    python3 ~/.vim/plugged/YouCompleteMe/install.py --all

    echo "!!! vim evn install success !!!"
}

main

